<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
Partial Class pfrmProductManagement
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(pfrmProductManagement))
        Dim BorderEdges1 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges2 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges3 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges4 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges5 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges6 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges7 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges8 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Dim BorderEdges9 As Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges = New Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges()
        Me.PCreateProd = New System.Windows.Forms.Panel()
        Me.Panel1 = New System.Windows.Forms.Panel()
        Me.BunifuButton11 = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.BunifuButton10 = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.BunifuButton9 = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.BunifuButton8 = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.btndelprod = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.btnchprice = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.btnmodprod = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.btncreateprod = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.BunifuButton1 = New Bunifu.UI.WinForms.BunifuButton.BunifuButton()
        Me.Panel1.SuspendLayout()
        Me.SuspendLayout()
        '
        'PCreateProd
        '
        Me.PCreateProd.AutoSize = True
        Me.PCreateProd.BackColor = System.Drawing.SystemColors.Control
        Me.PCreateProd.Dock = System.Windows.Forms.DockStyle.Fill
        Me.PCreateProd.Location = New System.Drawing.Point(219, 0)
        Me.PCreateProd.Name = "PCreateProd"
        Me.PCreateProd.Size = New System.Drawing.Size(754, 715)
        Me.PCreateProd.TabIndex = 3
        '
        'Panel1
        '
        Me.Panel1.BackColor = System.Drawing.Color.White
        Me.Panel1.Controls.Add(Me.BunifuButton11)
        Me.Panel1.Controls.Add(Me.BunifuButton10)
        Me.Panel1.Controls.Add(Me.BunifuButton9)
        Me.Panel1.Controls.Add(Me.BunifuButton8)
        Me.Panel1.Controls.Add(Me.btndelprod)
        Me.Panel1.Controls.Add(Me.btnchprice)
        Me.Panel1.Controls.Add(Me.btnmodprod)
        Me.Panel1.Controls.Add(Me.btncreateprod)
        Me.Panel1.Controls.Add(Me.BunifuButton1)
        Me.Panel1.Dock = System.Windows.Forms.DockStyle.Left
        Me.Panel1.Location = New System.Drawing.Point(0, 0)
        Me.Panel1.Name = "Panel1"
        Me.Panel1.Size = New System.Drawing.Size(219, 715)
        Me.Panel1.TabIndex = 2
        '
        'BunifuButton11
        '
        Me.BunifuButton11.AllowAnimations = True
        Me.BunifuButton11.AllowMouseEffects = True
        Me.BunifuButton11.AllowToggling = False
        Me.BunifuButton11.AnimationSpeed = 200
        Me.BunifuButton11.AutoGenerateColors = False
        Me.BunifuButton11.AutoRoundBorders = False
        Me.BunifuButton11.AutoSizeLeftIcon = True
        Me.BunifuButton11.AutoSizeRightIcon = True
        Me.BunifuButton11.BackColor = System.Drawing.Color.Transparent
        Me.BunifuButton11.BackColor1 = System.Drawing.Color.White
        Me.BunifuButton11.BackgroundImage = CType(resources.GetObject("BunifuButton11.BackgroundImage"), System.Drawing.Image)
        Me.BunifuButton11.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton11.ButtonText = "Print Barcodes"
        Me.BunifuButton11.ButtonTextMarginLeft = 0
        Me.BunifuButton11.ColorContrastOnClick = 45
        Me.BunifuButton11.ColorContrastOnHover = 45
        Me.BunifuButton11.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges1.BottomLeft = True
        BorderEdges1.BottomRight = True
        BorderEdges1.TopLeft = True
        BorderEdges1.TopRight = True
        Me.BunifuButton11.CustomizableEdges = BorderEdges1
        Me.BunifuButton11.DialogResult = System.Windows.Forms.DialogResult.None
        Me.BunifuButton11.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.BunifuButton11.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.BunifuButton11.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.BunifuButton11.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.BunifuButton11.Font = New System.Drawing.Font("Segoe UI", 12.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.BunifuButton11.ForeColor = System.Drawing.Color.Black
        Me.BunifuButton11.IconLeft = CType(resources.GetObject("BunifuButton11.IconLeft"), System.Drawing.Image)
        Me.BunifuButton11.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.BunifuButton11.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.BunifuButton11.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.BunifuButton11.IconMarginLeft = 11
        Me.BunifuButton11.IconPadding = 10
        Me.BunifuButton11.IconRight = Nothing
        Me.BunifuButton11.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.BunifuButton11.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.BunifuButton11.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.BunifuButton11.IconSize = 35
        Me.BunifuButton11.IdleBorderColor = System.Drawing.Color.White
        Me.BunifuButton11.IdleBorderRadius = 1
        Me.BunifuButton11.IdleBorderThickness = 1
        Me.BunifuButton11.IdleFillColor = System.Drawing.Color.White
        Me.BunifuButton11.IdleIconLeftImage = CType(resources.GetObject("BunifuButton11.IdleIconLeftImage"), System.Drawing.Image)
        Me.BunifuButton11.IdleIconRightImage = Nothing
        Me.BunifuButton11.IndicateFocus = False
        Me.BunifuButton11.Location = New System.Drawing.Point(0, 479)
        Me.BunifuButton11.Name = "BunifuButton11"
        Me.BunifuButton11.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.BunifuButton11.OnDisabledState.BorderRadius = 1
        Me.BunifuButton11.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton11.OnDisabledState.BorderThickness = 1
        Me.BunifuButton11.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.BunifuButton11.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.BunifuButton11.OnDisabledState.IconLeftImage = Nothing
        Me.BunifuButton11.OnDisabledState.IconRightImage = Nothing
        Me.BunifuButton11.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.BunifuButton11.onHoverState.BorderRadius = 1
        Me.BunifuButton11.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton11.onHoverState.BorderThickness = 1
        Me.BunifuButton11.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.BunifuButton11.onHoverState.ForeColor = System.Drawing.Color.White
        Me.BunifuButton11.onHoverState.IconLeftImage = Nothing
        Me.BunifuButton11.onHoverState.IconRightImage = Nothing
        Me.BunifuButton11.OnIdleState.BorderColor = System.Drawing.Color.White
        Me.BunifuButton11.OnIdleState.BorderRadius = 1
        Me.BunifuButton11.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton11.OnIdleState.BorderThickness = 1
        Me.BunifuButton11.OnIdleState.FillColor = System.Drawing.Color.White
        Me.BunifuButton11.OnIdleState.ForeColor = System.Drawing.Color.Black
        Me.BunifuButton11.OnIdleState.IconLeftImage = CType(resources.GetObject("BunifuButton11.OnIdleState.IconLeftImage"), System.Drawing.Image)
        Me.BunifuButton11.OnIdleState.IconRightImage = Nothing
        Me.BunifuButton11.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.BunifuButton11.OnPressedState.BorderRadius = 1
        Me.BunifuButton11.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton11.OnPressedState.BorderThickness = 1
        Me.BunifuButton11.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.BunifuButton11.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.BunifuButton11.OnPressedState.IconLeftImage = Nothing
        Me.BunifuButton11.OnPressedState.IconRightImage = Nothing
        Me.BunifuButton11.Size = New System.Drawing.Size(219, 49)
        Me.BunifuButton11.TabIndex = 173
        Me.BunifuButton11.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.BunifuButton11.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.BunifuButton11.TextMarginLeft = 0
        Me.BunifuButton11.TextPadding = New System.Windows.Forms.Padding(0)
        Me.BunifuButton11.UseDefaultRadiusAndThickness = True
        '
        'BunifuButton10
        '
        Me.BunifuButton10.AllowAnimations = True
        Me.BunifuButton10.AllowMouseEffects = True
        Me.BunifuButton10.AllowToggling = False
        Me.BunifuButton10.AnimationSpeed = 200
        Me.BunifuButton10.AutoGenerateColors = False
        Me.BunifuButton10.AutoRoundBorders = False
        Me.BunifuButton10.AutoSizeLeftIcon = True
        Me.BunifuButton10.AutoSizeRightIcon = True
        Me.BunifuButton10.BackColor = System.Drawing.Color.Transparent
        Me.BunifuButton10.BackColor1 = System.Drawing.Color.White
        Me.BunifuButton10.BackgroundImage = CType(resources.GetObject("BunifuButton10.BackgroundImage"), System.Drawing.Image)
        Me.BunifuButton10.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton10.ButtonText = "Price Band"
        Me.BunifuButton10.ButtonTextMarginLeft = 0
        Me.BunifuButton10.ColorContrastOnClick = 45
        Me.BunifuButton10.ColorContrastOnHover = 45
        Me.BunifuButton10.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges2.BottomLeft = True
        BorderEdges2.BottomRight = True
        BorderEdges2.TopLeft = True
        BorderEdges2.TopRight = True
        Me.BunifuButton10.CustomizableEdges = BorderEdges2
        Me.BunifuButton10.DialogResult = System.Windows.Forms.DialogResult.None
        Me.BunifuButton10.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.BunifuButton10.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.BunifuButton10.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.BunifuButton10.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.BunifuButton10.Font = New System.Drawing.Font("Segoe UI", 12.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.BunifuButton10.ForeColor = System.Drawing.Color.Black
        Me.BunifuButton10.IconLeft = CType(resources.GetObject("BunifuButton10.IconLeft"), System.Drawing.Image)
        Me.BunifuButton10.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.BunifuButton10.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.BunifuButton10.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.BunifuButton10.IconMarginLeft = 11
        Me.BunifuButton10.IconPadding = 10
        Me.BunifuButton10.IconRight = Nothing
        Me.BunifuButton10.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.BunifuButton10.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.BunifuButton10.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.BunifuButton10.IconSize = 35
        Me.BunifuButton10.IdleBorderColor = System.Drawing.Color.White
        Me.BunifuButton10.IdleBorderRadius = 1
        Me.BunifuButton10.IdleBorderThickness = 1
        Me.BunifuButton10.IdleFillColor = System.Drawing.Color.White
        Me.BunifuButton10.IdleIconLeftImage = CType(resources.GetObject("BunifuButton10.IdleIconLeftImage"), System.Drawing.Image)
        Me.BunifuButton10.IdleIconRightImage = Nothing
        Me.BunifuButton10.IndicateFocus = False
        Me.BunifuButton10.Location = New System.Drawing.Point(4, 373)
        Me.BunifuButton10.Name = "BunifuButton10"
        Me.BunifuButton10.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.BunifuButton10.OnDisabledState.BorderRadius = 1
        Me.BunifuButton10.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton10.OnDisabledState.BorderThickness = 1
        Me.BunifuButton10.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.BunifuButton10.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.BunifuButton10.OnDisabledState.IconLeftImage = Nothing
        Me.BunifuButton10.OnDisabledState.IconRightImage = Nothing
        Me.BunifuButton10.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.BunifuButton10.onHoverState.BorderRadius = 1
        Me.BunifuButton10.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton10.onHoverState.BorderThickness = 1
        Me.BunifuButton10.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.BunifuButton10.onHoverState.ForeColor = System.Drawing.Color.White
        Me.BunifuButton10.onHoverState.IconLeftImage = Nothing
        Me.BunifuButton10.onHoverState.IconRightImage = Nothing
        Me.BunifuButton10.OnIdleState.BorderColor = System.Drawing.Color.White
        Me.BunifuButton10.OnIdleState.BorderRadius = 1
        Me.BunifuButton10.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton10.OnIdleState.BorderThickness = 1
        Me.BunifuButton10.OnIdleState.FillColor = System.Drawing.Color.White
        Me.BunifuButton10.OnIdleState.ForeColor = System.Drawing.Color.Black
        Me.BunifuButton10.OnIdleState.IconLeftImage = CType(resources.GetObject("BunifuButton10.OnIdleState.IconLeftImage"), System.Drawing.Image)
        Me.BunifuButton10.OnIdleState.IconRightImage = Nothing
        Me.BunifuButton10.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.BunifuButton10.OnPressedState.BorderRadius = 1
        Me.BunifuButton10.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton10.OnPressedState.BorderThickness = 1
        Me.BunifuButton10.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.BunifuButton10.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.BunifuButton10.OnPressedState.IconLeftImage = Nothing
        Me.BunifuButton10.OnPressedState.IconRightImage = Nothing
        Me.BunifuButton10.Size = New System.Drawing.Size(215, 50)
        Me.BunifuButton10.TabIndex = 172
        Me.BunifuButton10.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.BunifuButton10.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.BunifuButton10.TextMarginLeft = 0
        Me.BunifuButton10.TextPadding = New System.Windows.Forms.Padding(0)
        Me.BunifuButton10.UseDefaultRadiusAndThickness = True
        '
        'BunifuButton9
        '
        Me.BunifuButton9.AllowAnimations = True
        Me.BunifuButton9.AllowMouseEffects = True
        Me.BunifuButton9.AllowToggling = False
        Me.BunifuButton9.AnimationSpeed = 200
        Me.BunifuButton9.AutoGenerateColors = False
        Me.BunifuButton9.AutoRoundBorders = False
        Me.BunifuButton9.AutoSizeLeftIcon = True
        Me.BunifuButton9.AutoSizeRightIcon = True
        Me.BunifuButton9.BackColor = System.Drawing.Color.Transparent
        Me.BunifuButton9.BackColor1 = System.Drawing.Color.White
        Me.BunifuButton9.BackgroundImage = CType(resources.GetObject("BunifuButton9.BackgroundImage"), System.Drawing.Image)
        Me.BunifuButton9.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton9.ButtonText = "Main Menu"
        Me.BunifuButton9.ButtonTextMarginLeft = 0
        Me.BunifuButton9.ColorContrastOnClick = 45
        Me.BunifuButton9.ColorContrastOnHover = 45
        Me.BunifuButton9.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges3.BottomLeft = True
        BorderEdges3.BottomRight = True
        BorderEdges3.TopLeft = True
        BorderEdges3.TopRight = True
        Me.BunifuButton9.CustomizableEdges = BorderEdges3
        Me.BunifuButton9.DialogResult = System.Windows.Forms.DialogResult.None
        Me.BunifuButton9.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.BunifuButton9.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.BunifuButton9.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.BunifuButton9.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.BunifuButton9.Font = New System.Drawing.Font("Segoe UI", 12.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.BunifuButton9.ForeColor = System.Drawing.Color.Black
        Me.BunifuButton9.IconLeft = CType(resources.GetObject("BunifuButton9.IconLeft"), System.Drawing.Image)
        Me.BunifuButton9.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.BunifuButton9.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.BunifuButton9.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.BunifuButton9.IconMarginLeft = 11
        Me.BunifuButton9.IconPadding = 10
        Me.BunifuButton9.IconRight = Nothing
        Me.BunifuButton9.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.BunifuButton9.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.BunifuButton9.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.BunifuButton9.IconSize = 35
        Me.BunifuButton9.IdleBorderColor = System.Drawing.Color.White
        Me.BunifuButton9.IdleBorderRadius = 1
        Me.BunifuButton9.IdleBorderThickness = 1
        Me.BunifuButton9.IdleFillColor = System.Drawing.Color.White
        Me.BunifuButton9.IdleIconLeftImage = CType(resources.GetObject("BunifuButton9.IdleIconLeftImage"), System.Drawing.Image)
        Me.BunifuButton9.IdleIconRightImage = Nothing
        Me.BunifuButton9.IndicateFocus = False
        Me.BunifuButton9.Location = New System.Drawing.Point(4, 50)
        Me.BunifuButton9.Name = "BunifuButton9"
        Me.BunifuButton9.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.BunifuButton9.OnDisabledState.BorderRadius = 1
        Me.BunifuButton9.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton9.OnDisabledState.BorderThickness = 1
        Me.BunifuButton9.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.BunifuButton9.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.BunifuButton9.OnDisabledState.IconLeftImage = Nothing
        Me.BunifuButton9.OnDisabledState.IconRightImage = Nothing
        Me.BunifuButton9.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.BunifuButton9.onHoverState.BorderRadius = 1
        Me.BunifuButton9.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton9.onHoverState.BorderThickness = 1
        Me.BunifuButton9.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.BunifuButton9.onHoverState.ForeColor = System.Drawing.Color.White
        Me.BunifuButton9.onHoverState.IconLeftImage = Nothing
        Me.BunifuButton9.onHoverState.IconRightImage = Nothing
        Me.BunifuButton9.OnIdleState.BorderColor = System.Drawing.Color.White
        Me.BunifuButton9.OnIdleState.BorderRadius = 1
        Me.BunifuButton9.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton9.OnIdleState.BorderThickness = 1
        Me.BunifuButton9.OnIdleState.FillColor = System.Drawing.Color.White
        Me.BunifuButton9.OnIdleState.ForeColor = System.Drawing.Color.Black
        Me.BunifuButton9.OnIdleState.IconLeftImage = CType(resources.GetObject("BunifuButton9.OnIdleState.IconLeftImage"), System.Drawing.Image)
        Me.BunifuButton9.OnIdleState.IconRightImage = Nothing
        Me.BunifuButton9.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.BunifuButton9.OnPressedState.BorderRadius = 1
        Me.BunifuButton9.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton9.OnPressedState.BorderThickness = 1
        Me.BunifuButton9.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.BunifuButton9.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.BunifuButton9.OnPressedState.IconLeftImage = Nothing
        Me.BunifuButton9.OnPressedState.IconRightImage = Nothing
        Me.BunifuButton9.Size = New System.Drawing.Size(215, 69)
        Me.BunifuButton9.TabIndex = 170
        Me.BunifuButton9.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.BunifuButton9.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.BunifuButton9.TextMarginLeft = 0
        Me.BunifuButton9.TextPadding = New System.Windows.Forms.Padding(0)
        Me.BunifuButton9.UseDefaultRadiusAndThickness = True
        '
        'BunifuButton8
        '
        Me.BunifuButton8.AllowAnimations = True
        Me.BunifuButton8.AllowMouseEffects = True
        Me.BunifuButton8.AllowToggling = False
        Me.BunifuButton8.AnimationSpeed = 200
        Me.BunifuButton8.AutoGenerateColors = False
        Me.BunifuButton8.AutoRoundBorders = False
        Me.BunifuButton8.AutoSizeLeftIcon = True
        Me.BunifuButton8.AutoSizeRightIcon = True
        Me.BunifuButton8.BackColor = System.Drawing.Color.Transparent
        Me.BunifuButton8.BackColor1 = System.Drawing.Color.White
        Me.BunifuButton8.BackgroundImage = CType(resources.GetObject("BunifuButton8.BackgroundImage"), System.Drawing.Image)
        Me.BunifuButton8.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton8.ButtonText = "Packages"
        Me.BunifuButton8.ButtonTextMarginLeft = 0
        Me.BunifuButton8.ColorContrastOnClick = 45
        Me.BunifuButton8.ColorContrastOnHover = 45
        Me.BunifuButton8.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges4.BottomLeft = True
        BorderEdges4.BottomRight = True
        BorderEdges4.TopLeft = True
        BorderEdges4.TopRight = True
        Me.BunifuButton8.CustomizableEdges = BorderEdges4
        Me.BunifuButton8.DialogResult = System.Windows.Forms.DialogResult.None
        Me.BunifuButton8.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.BunifuButton8.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.BunifuButton8.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.BunifuButton8.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.BunifuButton8.Font = New System.Drawing.Font("Segoe UI", 12.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.BunifuButton8.ForeColor = System.Drawing.Color.Black
        Me.BunifuButton8.IconLeft = CType(resources.GetObject("BunifuButton8.IconLeft"), System.Drawing.Image)
        Me.BunifuButton8.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.BunifuButton8.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.BunifuButton8.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.BunifuButton8.IconMarginLeft = 11
        Me.BunifuButton8.IconPadding = 10
        Me.BunifuButton8.IconRight = Nothing
        Me.BunifuButton8.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.BunifuButton8.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.BunifuButton8.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.BunifuButton8.IconSize = 35
        Me.BunifuButton8.IdleBorderColor = System.Drawing.Color.White
        Me.BunifuButton8.IdleBorderRadius = 1
        Me.BunifuButton8.IdleBorderThickness = 1
        Me.BunifuButton8.IdleFillColor = System.Drawing.Color.White
        Me.BunifuButton8.IdleIconLeftImage = CType(resources.GetObject("BunifuButton8.IdleIconLeftImage"), System.Drawing.Image)
        Me.BunifuButton8.IdleIconRightImage = Nothing
        Me.BunifuButton8.IndicateFocus = False
        Me.BunifuButton8.Location = New System.Drawing.Point(4, 423)
        Me.BunifuButton8.Name = "BunifuButton8"
        Me.BunifuButton8.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.BunifuButton8.OnDisabledState.BorderRadius = 1
        Me.BunifuButton8.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton8.OnDisabledState.BorderThickness = 1
        Me.BunifuButton8.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.BunifuButton8.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.BunifuButton8.OnDisabledState.IconLeftImage = Nothing
        Me.BunifuButton8.OnDisabledState.IconRightImage = Nothing
        Me.BunifuButton8.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.BunifuButton8.onHoverState.BorderRadius = 1
        Me.BunifuButton8.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton8.onHoverState.BorderThickness = 1
        Me.BunifuButton8.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.BunifuButton8.onHoverState.ForeColor = System.Drawing.Color.White
        Me.BunifuButton8.onHoverState.IconLeftImage = Nothing
        Me.BunifuButton8.onHoverState.IconRightImage = Nothing
        Me.BunifuButton8.OnIdleState.BorderColor = System.Drawing.Color.White
        Me.BunifuButton8.OnIdleState.BorderRadius = 1
        Me.BunifuButton8.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton8.OnIdleState.BorderThickness = 1
        Me.BunifuButton8.OnIdleState.FillColor = System.Drawing.Color.White
        Me.BunifuButton8.OnIdleState.ForeColor = System.Drawing.Color.Black
        Me.BunifuButton8.OnIdleState.IconLeftImage = CType(resources.GetObject("BunifuButton8.OnIdleState.IconLeftImage"), System.Drawing.Image)
        Me.BunifuButton8.OnIdleState.IconRightImage = Nothing
        Me.BunifuButton8.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.BunifuButton8.OnPressedState.BorderRadius = 1
        Me.BunifuButton8.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton8.OnPressedState.BorderThickness = 1
        Me.BunifuButton8.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.BunifuButton8.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.BunifuButton8.OnPressedState.IconLeftImage = Nothing
        Me.BunifuButton8.OnPressedState.IconRightImage = Nothing
        Me.BunifuButton8.Size = New System.Drawing.Size(215, 50)
        Me.BunifuButton8.TabIndex = 169
        Me.BunifuButton8.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.BunifuButton8.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.BunifuButton8.TextMarginLeft = 0
        Me.BunifuButton8.TextPadding = New System.Windows.Forms.Padding(0)
        Me.BunifuButton8.UseDefaultRadiusAndThickness = True
        '
        'btndelprod
        '
        Me.btndelprod.AllowAnimations = True
        Me.btndelprod.AllowMouseEffects = True
        Me.btndelprod.AllowToggling = False
        Me.btndelprod.AnimationSpeed = 200
        Me.btndelprod.AutoGenerateColors = False
        Me.btndelprod.AutoRoundBorders = False
        Me.btndelprod.AutoSizeLeftIcon = True
        Me.btndelprod.AutoSizeRightIcon = True
        Me.btndelprod.BackColor = System.Drawing.Color.Transparent
        Me.btndelprod.BackColor1 = System.Drawing.Color.White
        Me.btndelprod.BackgroundImage = CType(resources.GetObject("btndelprod.BackgroundImage"), System.Drawing.Image)
        Me.btndelprod.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btndelprod.ButtonText = "Delete Product"
        Me.btndelprod.ButtonTextMarginLeft = 0
        Me.btndelprod.ColorContrastOnClick = 45
        Me.btndelprod.ColorContrastOnHover = 45
        Me.btndelprod.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges5.BottomLeft = True
        BorderEdges5.BottomRight = True
        BorderEdges5.TopLeft = True
        BorderEdges5.TopRight = True
        Me.btndelprod.CustomizableEdges = BorderEdges5
        Me.btndelprod.DialogResult = System.Windows.Forms.DialogResult.None
        Me.btndelprod.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.btndelprod.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.btndelprod.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.btndelprod.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.btndelprod.Font = New System.Drawing.Font("Segoe UI", 12.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.btndelprod.ForeColor = System.Drawing.Color.Black
        Me.btndelprod.IconLeft = CType(resources.GetObject("btndelprod.IconLeft"), System.Drawing.Image)
        Me.btndelprod.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btndelprod.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.btndelprod.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.btndelprod.IconMarginLeft = 11
        Me.btndelprod.IconPadding = 10
        Me.btndelprod.IconRight = Nothing
        Me.btndelprod.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.btndelprod.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.btndelprod.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.btndelprod.IconSize = 35
        Me.btndelprod.IdleBorderColor = System.Drawing.Color.White
        Me.btndelprod.IdleBorderRadius = 1
        Me.btndelprod.IdleBorderThickness = 1
        Me.btndelprod.IdleFillColor = System.Drawing.Color.White
        Me.btndelprod.IdleIconLeftImage = CType(resources.GetObject("btndelprod.IdleIconLeftImage"), System.Drawing.Image)
        Me.btndelprod.IdleIconRightImage = Nothing
        Me.btndelprod.IndicateFocus = False
        Me.btndelprod.Location = New System.Drawing.Point(2, 324)
        Me.btndelprod.Name = "btndelprod"
        Me.btndelprod.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.btndelprod.OnDisabledState.BorderRadius = 1
        Me.btndelprod.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btndelprod.OnDisabledState.BorderThickness = 1
        Me.btndelprod.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.btndelprod.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.btndelprod.OnDisabledState.IconLeftImage = Nothing
        Me.btndelprod.OnDisabledState.IconRightImage = Nothing
        Me.btndelprod.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.btndelprod.onHoverState.BorderRadius = 1
        Me.btndelprod.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btndelprod.onHoverState.BorderThickness = 1
        Me.btndelprod.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.btndelprod.onHoverState.ForeColor = System.Drawing.Color.White
        Me.btndelprod.onHoverState.IconLeftImage = Nothing
        Me.btndelprod.onHoverState.IconRightImage = Nothing
        Me.btndelprod.OnIdleState.BorderColor = System.Drawing.Color.White
        Me.btndelprod.OnIdleState.BorderRadius = 1
        Me.btndelprod.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btndelprod.OnIdleState.BorderThickness = 1
        Me.btndelprod.OnIdleState.FillColor = System.Drawing.Color.White
        Me.btndelprod.OnIdleState.ForeColor = System.Drawing.Color.Black
        Me.btndelprod.OnIdleState.IconLeftImage = CType(resources.GetObject("btndelprod.OnIdleState.IconLeftImage"), System.Drawing.Image)
        Me.btndelprod.OnIdleState.IconRightImage = Nothing
        Me.btndelprod.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.btndelprod.OnPressedState.BorderRadius = 1
        Me.btndelprod.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btndelprod.OnPressedState.BorderThickness = 1
        Me.btndelprod.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.btndelprod.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.btndelprod.OnPressedState.IconLeftImage = Nothing
        Me.btndelprod.OnPressedState.IconRightImage = Nothing
        Me.btndelprod.Size = New System.Drawing.Size(219, 49)
        Me.btndelprod.TabIndex = 166
        Me.btndelprod.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.btndelprod.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.btndelprod.TextMarginLeft = 0
        Me.btndelprod.TextPadding = New System.Windows.Forms.Padding(0)
        Me.btndelprod.UseDefaultRadiusAndThickness = True
        '
        'btnchprice
        '
        Me.btnchprice.AllowAnimations = True
        Me.btnchprice.AllowMouseEffects = True
        Me.btnchprice.AllowToggling = False
        Me.btnchprice.AnimationSpeed = 200
        Me.btnchprice.AutoGenerateColors = False
        Me.btnchprice.AutoRoundBorders = False
        Me.btnchprice.AutoSizeLeftIcon = True
        Me.btnchprice.AutoSizeRightIcon = True
        Me.btnchprice.BackColor = System.Drawing.Color.Transparent
        Me.btnchprice.BackColor1 = System.Drawing.Color.White
        Me.btnchprice.BackgroundImage = CType(resources.GetObject("btnchprice.BackgroundImage"), System.Drawing.Image)
        Me.btnchprice.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btnchprice.ButtonText = "Change Price"
        Me.btnchprice.ButtonTextMarginLeft = 0
        Me.btnchprice.ColorContrastOnClick = 45
        Me.btnchprice.ColorContrastOnHover = 45
        Me.btnchprice.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges6.BottomLeft = True
        BorderEdges6.BottomRight = True
        BorderEdges6.TopLeft = True
        BorderEdges6.TopRight = True
        Me.btnchprice.CustomizableEdges = BorderEdges6
        Me.btnchprice.DialogResult = System.Windows.Forms.DialogResult.None
        Me.btnchprice.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.btnchprice.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.btnchprice.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.btnchprice.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.btnchprice.Font = New System.Drawing.Font("Segoe UI", 12.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.btnchprice.ForeColor = System.Drawing.Color.Black
        Me.btnchprice.IconLeft = CType(resources.GetObject("btnchprice.IconLeft"), System.Drawing.Image)
        Me.btnchprice.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnchprice.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.btnchprice.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.btnchprice.IconMarginLeft = 11
        Me.btnchprice.IconPadding = 10
        Me.btnchprice.IconRight = Nothing
        Me.btnchprice.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.btnchprice.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.btnchprice.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.btnchprice.IconSize = 35
        Me.btnchprice.IdleBorderColor = System.Drawing.Color.White
        Me.btnchprice.IdleBorderRadius = 1
        Me.btnchprice.IdleBorderThickness = 1
        Me.btnchprice.IdleFillColor = System.Drawing.Color.White
        Me.btnchprice.IdleIconLeftImage = CType(resources.GetObject("btnchprice.IdleIconLeftImage"), System.Drawing.Image)
        Me.btnchprice.IdleIconRightImage = Nothing
        Me.btnchprice.IndicateFocus = False
        Me.btnchprice.Location = New System.Drawing.Point(4, 269)
        Me.btnchprice.Name = "btnchprice"
        Me.btnchprice.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.btnchprice.OnDisabledState.BorderRadius = 1
        Me.btnchprice.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btnchprice.OnDisabledState.BorderThickness = 1
        Me.btnchprice.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.btnchprice.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.btnchprice.OnDisabledState.IconLeftImage = Nothing
        Me.btnchprice.OnDisabledState.IconRightImage = Nothing
        Me.btnchprice.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.btnchprice.onHoverState.BorderRadius = 1
        Me.btnchprice.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btnchprice.onHoverState.BorderThickness = 1
        Me.btnchprice.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.btnchprice.onHoverState.ForeColor = System.Drawing.Color.White
        Me.btnchprice.onHoverState.IconLeftImage = Nothing
        Me.btnchprice.onHoverState.IconRightImage = Nothing
        Me.btnchprice.OnIdleState.BorderColor = System.Drawing.Color.White
        Me.btnchprice.OnIdleState.BorderRadius = 1
        Me.btnchprice.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btnchprice.OnIdleState.BorderThickness = 1
        Me.btnchprice.OnIdleState.FillColor = System.Drawing.Color.White
        Me.btnchprice.OnIdleState.ForeColor = System.Drawing.Color.Black
        Me.btnchprice.OnIdleState.IconLeftImage = CType(resources.GetObject("btnchprice.OnIdleState.IconLeftImage"), System.Drawing.Image)
        Me.btnchprice.OnIdleState.IconRightImage = Nothing
        Me.btnchprice.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.btnchprice.OnPressedState.BorderRadius = 1
        Me.btnchprice.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btnchprice.OnPressedState.BorderThickness = 1
        Me.btnchprice.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.btnchprice.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.btnchprice.OnPressedState.IconLeftImage = Nothing
        Me.btnchprice.OnPressedState.IconRightImage = Nothing
        Me.btnchprice.Size = New System.Drawing.Size(215, 55)
        Me.btnchprice.TabIndex = 165
        Me.btnchprice.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.btnchprice.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.btnchprice.TextMarginLeft = 0
        Me.btnchprice.TextPadding = New System.Windows.Forms.Padding(0)
        Me.btnchprice.UseDefaultRadiusAndThickness = True
        '
        'btnmodprod
        '
        Me.btnmodprod.AllowAnimations = True
        Me.btnmodprod.AllowMouseEffects = True
        Me.btnmodprod.AllowToggling = False
        Me.btnmodprod.AnimationSpeed = 200
        Me.btnmodprod.AutoGenerateColors = False
        Me.btnmodprod.AutoRoundBorders = False
        Me.btnmodprod.AutoSizeLeftIcon = True
        Me.btnmodprod.AutoSizeRightIcon = True
        Me.btnmodprod.BackColor = System.Drawing.Color.Transparent
        Me.btnmodprod.BackColor1 = System.Drawing.Color.White
        Me.btnmodprod.BackgroundImage = CType(resources.GetObject("btnmodprod.BackgroundImage"), System.Drawing.Image)
        Me.btnmodprod.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btnmodprod.ButtonText = "Modify Product"
        Me.btnmodprod.ButtonTextMarginLeft = 0
        Me.btnmodprod.ColorContrastOnClick = 45
        Me.btnmodprod.ColorContrastOnHover = 45
        Me.btnmodprod.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges7.BottomLeft = True
        BorderEdges7.BottomRight = True
        BorderEdges7.TopLeft = True
        BorderEdges7.TopRight = True
        Me.btnmodprod.CustomizableEdges = BorderEdges7
        Me.btnmodprod.DialogResult = System.Windows.Forms.DialogResult.None
        Me.btnmodprod.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.btnmodprod.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.btnmodprod.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.btnmodprod.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.btnmodprod.Font = New System.Drawing.Font("Segoe UI", 12.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.btnmodprod.ForeColor = System.Drawing.Color.Black
        Me.btnmodprod.IconLeft = CType(resources.GetObject("btnmodprod.IconLeft"), System.Drawing.Image)
        Me.btnmodprod.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btnmodprod.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.btnmodprod.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.btnmodprod.IconMarginLeft = 11
        Me.btnmodprod.IconPadding = 10
        Me.btnmodprod.IconRight = Nothing
        Me.btnmodprod.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.btnmodprod.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.btnmodprod.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.btnmodprod.IconSize = 35
        Me.btnmodprod.IdleBorderColor = System.Drawing.Color.White
        Me.btnmodprod.IdleBorderRadius = 1
        Me.btnmodprod.IdleBorderThickness = 1
        Me.btnmodprod.IdleFillColor = System.Drawing.Color.White
        Me.btnmodprod.IdleIconLeftImage = CType(resources.GetObject("btnmodprod.IdleIconLeftImage"), System.Drawing.Image)
        Me.btnmodprod.IdleIconRightImage = Nothing
        Me.btnmodprod.IndicateFocus = False
        Me.btnmodprod.Location = New System.Drawing.Point(4, 219)
        Me.btnmodprod.Name = "btnmodprod"
        Me.btnmodprod.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.btnmodprod.OnDisabledState.BorderRadius = 1
        Me.btnmodprod.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btnmodprod.OnDisabledState.BorderThickness = 1
        Me.btnmodprod.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.btnmodprod.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.btnmodprod.OnDisabledState.IconLeftImage = Nothing
        Me.btnmodprod.OnDisabledState.IconRightImage = Nothing
        Me.btnmodprod.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.btnmodprod.onHoverState.BorderRadius = 1
        Me.btnmodprod.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btnmodprod.onHoverState.BorderThickness = 1
        Me.btnmodprod.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.btnmodprod.onHoverState.ForeColor = System.Drawing.Color.White
        Me.btnmodprod.onHoverState.IconLeftImage = Nothing
        Me.btnmodprod.onHoverState.IconRightImage = Nothing
        Me.btnmodprod.OnIdleState.BorderColor = System.Drawing.Color.White
        Me.btnmodprod.OnIdleState.BorderRadius = 1
        Me.btnmodprod.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btnmodprod.OnIdleState.BorderThickness = 1
        Me.btnmodprod.OnIdleState.FillColor = System.Drawing.Color.White
        Me.btnmodprod.OnIdleState.ForeColor = System.Drawing.Color.Black
        Me.btnmodprod.OnIdleState.IconLeftImage = CType(resources.GetObject("btnmodprod.OnIdleState.IconLeftImage"), System.Drawing.Image)
        Me.btnmodprod.OnIdleState.IconRightImage = Nothing
        Me.btnmodprod.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.btnmodprod.OnPressedState.BorderRadius = 1
        Me.btnmodprod.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btnmodprod.OnPressedState.BorderThickness = 1
        Me.btnmodprod.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.btnmodprod.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.btnmodprod.OnPressedState.IconLeftImage = Nothing
        Me.btnmodprod.OnPressedState.IconRightImage = Nothing
        Me.btnmodprod.Size = New System.Drawing.Size(215, 50)
        Me.btnmodprod.TabIndex = 164
        Me.btnmodprod.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.btnmodprod.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.btnmodprod.TextMarginLeft = 0
        Me.btnmodprod.TextPadding = New System.Windows.Forms.Padding(0)
        Me.btnmodprod.UseDefaultRadiusAndThickness = True
        '
        'btncreateprod
        '
        Me.btncreateprod.AllowAnimations = True
        Me.btncreateprod.AllowMouseEffects = True
        Me.btncreateprod.AllowToggling = False
        Me.btncreateprod.AnimationSpeed = 200
        Me.btncreateprod.AutoGenerateColors = False
        Me.btncreateprod.AutoRoundBorders = False
        Me.btncreateprod.AutoSizeLeftIcon = True
        Me.btncreateprod.AutoSizeRightIcon = True
        Me.btncreateprod.BackColor = System.Drawing.Color.Transparent
        Me.btncreateprod.BackColor1 = System.Drawing.Color.White
        Me.btncreateprod.BackgroundImage = CType(resources.GetObject("btncreateprod.BackgroundImage"), System.Drawing.Image)
        Me.btncreateprod.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btncreateprod.ButtonText = "Create Product"
        Me.btncreateprod.ButtonTextMarginLeft = 0
        Me.btncreateprod.ColorContrastOnClick = 45
        Me.btncreateprod.ColorContrastOnHover = 45
        Me.btncreateprod.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges8.BottomLeft = True
        BorderEdges8.BottomRight = True
        BorderEdges8.TopLeft = True
        BorderEdges8.TopRight = True
        Me.btncreateprod.CustomizableEdges = BorderEdges8
        Me.btncreateprod.DialogResult = System.Windows.Forms.DialogResult.None
        Me.btncreateprod.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.btncreateprod.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.btncreateprod.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.btncreateprod.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.btncreateprod.Font = New System.Drawing.Font("Segoe UI", 12.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.btncreateprod.ForeColor = System.Drawing.Color.Black
        Me.btncreateprod.IconLeft = CType(resources.GetObject("btncreateprod.IconLeft"), System.Drawing.Image)
        Me.btncreateprod.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.btncreateprod.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.btncreateprod.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.btncreateprod.IconMarginLeft = 11
        Me.btncreateprod.IconPadding = 10
        Me.btncreateprod.IconRight = Nothing
        Me.btncreateprod.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.btncreateprod.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.btncreateprod.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.btncreateprod.IconSize = 35
        Me.btncreateprod.IdleBorderColor = System.Drawing.Color.White
        Me.btncreateprod.IdleBorderRadius = 1
        Me.btncreateprod.IdleBorderThickness = 1
        Me.btncreateprod.IdleFillColor = System.Drawing.Color.White
        Me.btncreateprod.IdleIconLeftImage = CType(resources.GetObject("btncreateprod.IdleIconLeftImage"), System.Drawing.Image)
        Me.btncreateprod.IdleIconRightImage = Nothing
        Me.btncreateprod.IndicateFocus = False
        Me.btncreateprod.Location = New System.Drawing.Point(4, 171)
        Me.btncreateprod.Name = "btncreateprod"
        Me.btncreateprod.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.btncreateprod.OnDisabledState.BorderRadius = 1
        Me.btncreateprod.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btncreateprod.OnDisabledState.BorderThickness = 1
        Me.btncreateprod.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.btncreateprod.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.btncreateprod.OnDisabledState.IconLeftImage = Nothing
        Me.btncreateprod.OnDisabledState.IconRightImage = Nothing
        Me.btncreateprod.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.btncreateprod.onHoverState.BorderRadius = 1
        Me.btncreateprod.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btncreateprod.onHoverState.BorderThickness = 1
        Me.btncreateprod.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.btncreateprod.onHoverState.ForeColor = System.Drawing.Color.White
        Me.btncreateprod.onHoverState.IconLeftImage = Nothing
        Me.btncreateprod.onHoverState.IconRightImage = Nothing
        Me.btncreateprod.OnIdleState.BorderColor = System.Drawing.Color.White
        Me.btncreateprod.OnIdleState.BorderRadius = 1
        Me.btncreateprod.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btncreateprod.OnIdleState.BorderThickness = 1
        Me.btncreateprod.OnIdleState.FillColor = System.Drawing.Color.White
        Me.btncreateprod.OnIdleState.ForeColor = System.Drawing.Color.Black
        Me.btncreateprod.OnIdleState.IconLeftImage = CType(resources.GetObject("btncreateprod.OnIdleState.IconLeftImage"), System.Drawing.Image)
        Me.btncreateprod.OnIdleState.IconRightImage = Nothing
        Me.btncreateprod.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.btncreateprod.OnPressedState.BorderRadius = 1
        Me.btncreateprod.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.btncreateprod.OnPressedState.BorderThickness = 1
        Me.btncreateprod.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.btncreateprod.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.btncreateprod.OnPressedState.IconLeftImage = Nothing
        Me.btncreateprod.OnPressedState.IconRightImage = Nothing
        Me.btncreateprod.Size = New System.Drawing.Size(215, 48)
        Me.btncreateprod.TabIndex = 163
        Me.btncreateprod.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.btncreateprod.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.btncreateprod.TextMarginLeft = 0
        Me.btncreateprod.TextPadding = New System.Windows.Forms.Padding(0)
        Me.btncreateprod.UseDefaultRadiusAndThickness = True
        '
        'BunifuButton1
        '
        Me.BunifuButton1.AllowAnimations = True
        Me.BunifuButton1.AllowMouseEffects = True
        Me.BunifuButton1.AllowToggling = False
        Me.BunifuButton1.AnimationSpeed = 200
        Me.BunifuButton1.AutoGenerateColors = False
        Me.BunifuButton1.AutoRoundBorders = False
        Me.BunifuButton1.AutoSizeLeftIcon = True
        Me.BunifuButton1.AutoSizeRightIcon = True
        Me.BunifuButton1.BackColor = System.Drawing.Color.Transparent
        Me.BunifuButton1.BackColor1 = System.Drawing.Color.White
        Me.BunifuButton1.BackgroundImage = CType(resources.GetObject("BunifuButton1.BackgroundImage"), System.Drawing.Image)
        Me.BunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton1.ButtonText = "Dashboard"
        Me.BunifuButton1.ButtonTextMarginLeft = 0
        Me.BunifuButton1.ColorContrastOnClick = 45
        Me.BunifuButton1.ColorContrastOnHover = 45
        Me.BunifuButton1.Cursor = System.Windows.Forms.Cursors.Default
        BorderEdges9.BottomLeft = True
        BorderEdges9.BottomRight = True
        BorderEdges9.TopLeft = True
        BorderEdges9.TopRight = True
        Me.BunifuButton1.CustomizableEdges = BorderEdges9
        Me.BunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None
        Me.BunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.BunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.BunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.BunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed
        Me.BunifuButton1.Font = New System.Drawing.Font("Segoe UI", 12.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.BunifuButton1.ForeColor = System.Drawing.Color.Black
        Me.BunifuButton1.IconLeft = CType(resources.GetObject("BunifuButton1.IconLeft"), System.Drawing.Image)
        Me.BunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft
        Me.BunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default
        Me.BunifuButton1.IconLeftPadding = New System.Windows.Forms.Padding(11, 3, 3, 3)
        Me.BunifuButton1.IconMarginLeft = 11
        Me.BunifuButton1.IconPadding = 10
        Me.BunifuButton1.IconRight = Nothing
        Me.BunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight
        Me.BunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default
        Me.BunifuButton1.IconRightPadding = New System.Windows.Forms.Padding(3, 3, 7, 3)
        Me.BunifuButton1.IconSize = 35
        Me.BunifuButton1.IdleBorderColor = System.Drawing.Color.White
        Me.BunifuButton1.IdleBorderRadius = 1
        Me.BunifuButton1.IdleBorderThickness = 1
        Me.BunifuButton1.IdleFillColor = System.Drawing.Color.White
        Me.BunifuButton1.IdleIconLeftImage = CType(resources.GetObject("BunifuButton1.IdleIconLeftImage"), System.Drawing.Image)
        Me.BunifuButton1.IdleIconRightImage = Nothing
        Me.BunifuButton1.IndicateFocus = False
        Me.BunifuButton1.Location = New System.Drawing.Point(4, 119)
        Me.BunifuButton1.Name = "BunifuButton1"
        Me.BunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer), CType(CType(191, Byte), Integer))
        Me.BunifuButton1.OnDisabledState.BorderRadius = 1
        Me.BunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton1.OnDisabledState.BorderThickness = 1
        Me.BunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer), CType(CType(204, Byte), Integer))
        Me.BunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(CType(CType(168, Byte), Integer), CType(CType(160, Byte), Integer), CType(CType(168, Byte), Integer))
        Me.BunifuButton1.OnDisabledState.IconLeftImage = Nothing
        Me.BunifuButton1.OnDisabledState.IconRightImage = Nothing
        Me.BunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.BunifuButton1.onHoverState.BorderRadius = 1
        Me.BunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton1.onHoverState.BorderThickness = 1
        Me.BunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(CType(CType(105, Byte), Integer), CType(CType(181, Byte), Integer), CType(CType(255, Byte), Integer))
        Me.BunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White
        Me.BunifuButton1.onHoverState.IconLeftImage = Nothing
        Me.BunifuButton1.onHoverState.IconRightImage = Nothing
        Me.BunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.White
        Me.BunifuButton1.OnIdleState.BorderRadius = 1
        Me.BunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton1.OnIdleState.BorderThickness = 1
        Me.BunifuButton1.OnIdleState.FillColor = System.Drawing.Color.White
        Me.BunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.Black
        Me.BunifuButton1.OnIdleState.IconLeftImage = CType(resources.GetObject("BunifuButton1.OnIdleState.IconLeftImage"), System.Drawing.Image)
        Me.BunifuButton1.OnIdleState.IconRightImage = Nothing
        Me.BunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.BunifuButton1.OnPressedState.BorderRadius = 1
        Me.BunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid
        Me.BunifuButton1.OnPressedState.BorderThickness = 1
        Me.BunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(CType(CType(40, Byte), Integer), CType(CType(96, Byte), Integer), CType(CType(144, Byte), Integer))
        Me.BunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White
        Me.BunifuButton1.OnPressedState.IconLeftImage = Nothing
        Me.BunifuButton1.OnPressedState.IconRightImage = Nothing
        Me.BunifuButton1.Size = New System.Drawing.Size(215, 52)
        Me.BunifuButton1.TabIndex = 162
        Me.BunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter
        Me.BunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center
        Me.BunifuButton1.TextMarginLeft = 0
        Me.BunifuButton1.TextPadding = New System.Windows.Forms.Padding(0)
        Me.BunifuButton1.UseDefaultRadiusAndThickness = True
        Me.BunifuButton1.Visible = False
        '
        'pfrmProductManagement
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.AutoScroll = True
        Me.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink
        Me.ClientSize = New System.Drawing.Size(973, 715)
        Me.Controls.Add(Me.PCreateProd)
        Me.Controls.Add(Me.Panel1)
        Me.Icon = CType(resources.GetObject("$this.Icon"), System.Drawing.Icon)
        Me.Name = "pfrmProductManagement"
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "Product Management"
        Me.Panel1.ResumeLayout(False)
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub

    Friend WithEvents PCreateProd As Panel
    Friend WithEvents Panel1 As Panel
    Friend WithEvents BunifuButton1 As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents btncreateprod As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents btnmodprod As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents btnchprice As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents btndelprod As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents BunifuButton8 As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents BunifuButton9 As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents BunifuButton10 As Bunifu.UI.WinForms.BunifuButton.BunifuButton
    Friend WithEvents BunifuButton11 As Bunifu.UI.WinForms.BunifuButton.BunifuButton
End Class
